<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Servicios\Servicios.csproj" />
    <ProjectReference Include="..\BiblioConDapper\BiblioConDapper.csproj" />
  </ItemGroup>
</Project>